<?php
$_productCollection = Mage::getModel('catalog/product')->getCollection();
$_productCollection->addAttributeToSelect(array(
                                   'image',
                                   'name',
                                   'short_description'
                   ))
                   ->addFieldToFilter('visibility', array(
                               Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,
                               Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG
                   )) //showing just products visible in catalog or both search and catalog
                   ->addFinalPrice()
//                        ->addAttributeToSort('price', 'asc') //in case we would like to sort products by price
                   ->getSelect()
                   ->where('price_index.final_price < price_index.price')
                        ->limit(20) //we can specify how many products we want to show on this page
                        ->order(new Zend_Db_Expr('RAND()')) //in case we would like to sort products randomly
                   ;
 
Mage::getModel('review/review')->appendSummary($_productCollection);
 
$_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<!-- Set up your HTML -->
<div class="owl-carousel sale-product">
	<?php // List mode ?>
	<?php $_iterator = 0; ?>				
	<?php foreach ($_productCollection as $_product): ?>
		<div class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
			<div class="bgf-color" style="background: <?php echo '#' . Mage::helper('productslider')->getSaleBackGround() ?>">
				<p style="color:<?php echo '#' . Mage::helper('productslider')->getSaleTextColor() ?>"><?php echo Mage::helper('productslider')->getSaleLabel() ?></p>
			</div>
			<?php // Product Image ?>
			<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">			
				<img src="<?php echo $_product->getImageUrl(); ?>" width="226" height="226" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
			</a>
			<?php // Product description ?>
			<div class="product-info">								
				<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
				<h3 class="product-name">
					<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a>
				</h3>
				<p class="description">
					<?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
				</p>
				<?php echo $this->getPriceHtml($_product, true) ?>
				<div class="actions">
					<?php if($_product->isSaleable()): ?>
						<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span>
						</button>
					<?php else: ?>
						<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
					<?php endif; ?>
				</div>
			</div>
		</div>
	<?php endforeach; ?>
	<script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
</div>
<?php endif; ?>
<script>
jQuery(document).ready(function(){
  jQuery(".owl-carousel").owlCarousel();
});
</script>